# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd hist_ignore_all_dups
setopt appendhistory share_history autocd extendedglob nomatch notify
unsetopt beep
unsetopt CASE_GLOB

bindkey -e
#bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^i' expand-or-complete-prefix
#bindkey  "\e[2~" quoted-insert
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename '/home/user/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall

# Added by user here.
REPORTTIME=10

alias ls="ls $LS_OPTIONS"
alias gits='git status'

lsp ()
{
	ls -1 "/var/log/packages/$@"* |xargs -i basename {}
}

#%{\e[0;31m%}%m%{\e[0m%}
#source /usr/doc/git-2.20.1/contrib/completion/git-prompt.sh   #on Slackware
# source /usr/share/git-core/contrib/completion/git-prompt.sh
#setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '
export PS1="%? [%~]
 %# "

export PATH=$HOME/bin:$PATH:/sbin:/usr/sbin

# Powerline
#. /usr/local/repo/powerline/powerline/bindings/zsh/powerline.zsh
#

# Tmux
# If not running interactively, do not do anything
#[[ $- != *i* ]] && return
#[[ -z "$TMUX" ]] && exec tmux
#
## export https_proxy=http://localhost:8118
